import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar"
import Footer from "./components/Footer";
import { WalletProvider } from "@/app/components/ui/WalletProvider";
import { Toast } from "@/app/components/ui/toast";
import { WrongNetworkAlert } from "@/app/components/ui/WrongNetworkAlert";
import { ReactQueryProvider } from "@/app/components/ui/ReactQueryProvider";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ScholarNest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WalletProvider>
          <ReactQueryProvider>
        <Navbar/>
        {children}
        <Footer/>
        </ReactQueryProvider>
        </WalletProvider>
      </body>
    </html>
  );
}
